remote_theme: ISSAE/architect

name: Programmation Avancée ED3

author: Pascal Fares

author_email: pascal.fares@isae.edu.lb

title: Programmation événementille et MVC Swing
description: Programmation Avancée et Patron de conception en Java

google_analytics: UA-29708002-2

repository: ISSAE/nfp121.ed3

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

